version: 2
updates:
  - package-ecosystem: npm
    directory: /face-attendance/frontend
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /face-attendance/backend
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /face-attendance/ai-service
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /face-attendance/ai-service
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
