"""Make student details optional

Revision ID: 1bdf04ea2588
Revises: feaae3d98fe3
Create Date: 2026-09-01 02:58:54.596386
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1bdf04ea2588'
down_revision: str | None = 'feaae3d98fe3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'student_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('students', 'parent_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('students', 'parent_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'parent_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('students', 'parent_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('students', 'student_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
