"""Add session_type

Revision ID: 35f101730b0f
Revises: f6609d33ec78
Create Date: 2026-07-20 15:01:48.739664
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '35f101730b0f'
down_revision: str | None = 'f6609d33ec78'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_sessions', sa.Column('session_type', sa.String(length=20), server_default='check_in', nullable=False))
    op.drop_index(op.f('uq_attendance_sessions_one_active_company'), table_name='attendance_sessions', postgresql_where="(((status)::text = 'active'::text) AND (stopped_at IS NULL))")
    op.create_index('uq_attendance_sessions_one_active_company_per_type', 'attendance_sessions', ['company_id', 'session_type'], unique=True, postgresql_where=sa.text("status = 'active' AND stopped_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_attendance_sessions_one_active_company_per_type', table_name='attendance_sessions', postgresql_where=sa.text("status = 'active' AND stopped_at IS NULL"))
    op.create_index(op.f('uq_attendance_sessions_one_active_company'), 'attendance_sessions', ['company_id'], unique=True, postgresql_where="(((status)::text = 'active'::text) AND (stopped_at IS NULL))")
    op.drop_column('attendance_sessions', 'session_type')
    # ### end Alembic commands ###
