"""remove_whatsapp

Revision ID: 4fb6932efb74
Revises: h2i3j4k5l6m7
Create Date: 2026-08-24 02:22:22.279516
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4fb6932efb74'
down_revision: str | None = 'h2i3j4k5l6m7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_logs_created_at'), table_name='whatsapp_logs')
    op.drop_index(op.f('ix_whatsapp_logs_employee_id'), table_name='whatsapp_logs')
    op.drop_index(op.f('ix_whatsapp_logs_id'), table_name='whatsapp_logs')
    op.drop_index(op.f('ix_whatsapp_logs_message_type'), table_name='whatsapp_logs')
    op.drop_index(op.f('ix_whatsapp_logs_parent_phone'), table_name='whatsapp_logs')
    op.drop_index(op.f('ix_whatsapp_logs_school_id'), table_name='whatsapp_logs')
    op.drop_index(op.f('ix_whatsapp_logs_status'), table_name='whatsapp_logs')
    op.drop_index(op.f('ix_whatsapp_logs_student_id'), table_name='whatsapp_logs')
    op.drop_table('whatsapp_logs')
    op.drop_index(op.f('ix_whatsapp_inbound_messages_created_at'), table_name='whatsapp_inbound_messages')
    op.drop_index(op.f('ix_whatsapp_inbound_messages_id'), table_name='whatsapp_inbound_messages')
    op.drop_index(op.f('ix_whatsapp_inbound_messages_meta_message_id'), table_name='whatsapp_inbound_messages')
    op.drop_index(op.f('ix_whatsapp_inbound_messages_phone_number_id'), table_name='whatsapp_inbound_messages')
    op.drop_index(op.f('ix_whatsapp_inbound_messages_school_id'), table_name='whatsapp_inbound_messages')
    op.drop_index(op.f('ix_whatsapp_inbound_messages_sender_phone'), table_name='whatsapp_inbound_messages')
    op.drop_index(op.f('ix_whatsapp_inbound_messages_student_id'), table_name='whatsapp_inbound_messages')
    op.drop_table('whatsapp_inbound_messages')
    op.drop_column('companies', 'whatsapp_token')
    op.drop_column('companies', 'whatsapp_phone_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('whatsapp_phone_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('whatsapp_token', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.create_table('whatsapp_inbound_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meta_message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone_number_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sender_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('message_body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['companies.id'], name=op.f('whatsapp_inbound_messages_school_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('whatsapp_inbound_messages_student_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('whatsapp_inbound_messages_pkey'))
    )
    op.create_index(op.f('ix_whatsapp_inbound_messages_student_id'), 'whatsapp_inbound_messages', ['student_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_inbound_messages_sender_phone'), 'whatsapp_inbound_messages', ['sender_phone'], unique=False)
    op.create_index(op.f('ix_whatsapp_inbound_messages_school_id'), 'whatsapp_inbound_messages', ['school_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_inbound_messages_phone_number_id'), 'whatsapp_inbound_messages', ['phone_number_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_inbound_messages_meta_message_id'), 'whatsapp_inbound_messages', ['meta_message_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_inbound_messages_id'), 'whatsapp_inbound_messages', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_inbound_messages_created_at'), 'whatsapp_inbound_messages', ['created_at'], unique=False)
    op.create_table('whatsapp_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message_body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('meta_message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_whatsapp_logs_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['companies.id'], name=op.f('whatsapp_logs_school_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('whatsapp_logs_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('whatsapp_logs_pkey'))
    )
    op.create_index(op.f('ix_whatsapp_logs_student_id'), 'whatsapp_logs', ['student_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_logs_status'), 'whatsapp_logs', ['status'], unique=False)
    op.create_index(op.f('ix_whatsapp_logs_school_id'), 'whatsapp_logs', ['school_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_logs_parent_phone'), 'whatsapp_logs', ['parent_phone'], unique=False)
    op.create_index(op.f('ix_whatsapp_logs_message_type'), 'whatsapp_logs', ['message_type'], unique=False)
    op.create_index(op.f('ix_whatsapp_logs_id'), 'whatsapp_logs', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_logs_employee_id'), 'whatsapp_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_logs_created_at'), 'whatsapp_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
