"""Add timestamps and fix unique constraints

Revision ID: 9428e714984a
Revises: 4bb92f37879c
Create Date: 2026-06-27 14:28:03.236844
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9428e714984a'
down_revision: str | None = '4bb92f37879c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('branches', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('employees', sa.Column('headshot_url', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('employees', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_unique_constraint('uq_company_employee_email', 'employees', ['company_id', 'email'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint('uq_company_employee_email', 'employees', type_='unique')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'created_at')
    op.drop_column('employees', 'headshot_url')
    op.drop_column('companies', 'updated_at')
    op.drop_column('branches', 'updated_at')
    op.drop_column('branches', 'created_at')
    # ### end Alembic commands ###
