"""Add hr_email to Company

Revision ID: c7179d6bc5e4
Revises: 1bdf04ea2588
Create Date: 2026-09-01 03:08:20.782002
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c7179d6bc5e4'
down_revision: str | None = '1bdf04ea2588'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('hr_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'hr_email')
    # ### end Alembic commands ###
