"""Make branch_id nullable and update unique index for company-wide sessions

Revision ID: f6609d33ec78
Revises: c1d4e7f9a620
Create Date: 2026-07-20 14:10:17.789182
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f6609d33ec78'
down_revision: str | None = 'c1d4e7f9a620'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_sessions', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_attendance_sessions_active_class'), table_name='attendance_sessions')
    op.drop_index(op.f('uq_attendance_sessions_one_active_class'), table_name='attendance_sessions', postgresql_where="(((status)::text = 'active'::text) AND (stopped_at IS NULL))")
    op.create_index('ix_attendance_sessions_active_company', 'attendance_sessions', ['company_id', 'status'], unique=False)
    op.create_index('uq_attendance_sessions_one_active_company', 'attendance_sessions', ['company_id'], unique=True, postgresql_where=sa.text("status = 'active' AND stopped_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_attendance_sessions_one_active_company', table_name='attendance_sessions', postgresql_where=sa.text("status = 'active' AND stopped_at IS NULL"))
    op.drop_index('ix_attendance_sessions_active_company', table_name='attendance_sessions')
    op.create_index(op.f('uq_attendance_sessions_one_active_class'), 'attendance_sessions', ['company_id', 'branch_id'], unique=True, postgresql_where="(((status)::text = 'active'::text) AND (stopped_at IS NULL))")
    op.create_index(op.f('ix_attendance_sessions_active_class'), 'attendance_sessions', ['company_id', 'branch_id', 'status'], unique=False)
    op.alter_column('attendance_sessions', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
