"""add default_session_duration_minutes to companies

Revision ID: feaae3d98fe3
Revises: 71e5fc68540d
Create Date: 2026-08-28 00:32:11.604126
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'feaae3d98fe3'
down_revision: str | None = '71e5fc68540d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('default_session_duration_minutes', sa.Integer(), server_default='60', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'default_session_duration_minutes')
    # ### end Alembic commands ###
